### DISCUSSION TITLE
The future of Wrangler configuration

### DISCUSSION THREAD

**Discussion by penalosa** [cloudflare/workers-sdk#1951] [RFCs]
Following on from https://github.com/cloudflare/wrangler2/pull/1929 —it's probably worthwhile having a discussion about the future of configuration for Wrangler, pulling together the various discussions there have been at different points. The linked PR shows one approach—wholesale migrating from TOML->JSON—but I know there are different opinions to be heard here. From my own thinking (to kick this off):
1. It's useful for Wrangler to have a configuration file
2. TOML is rarely used in the Javascript ecosystem, and has various footguns that lead to hard to understand errors (array closing being the primary one that comes to mind)
3. JSON (or JSONC/JSON5) is more easily understandable, and is harder to write incorrectly (and we could leverage things like JSON schema to provide schema error checking in people's IDEs)
4. The API-ification of Wrangler is another possible way forward here, with something like a `wrangler.ts` or `wrangler.js` file that describes the configuration of your Worker (but see point 1, this can't be the only way)

The outcome of this discussion could well be that we decide to stick with TOML, but I thought it was worth airing all the various thoughts on this in one place, rather than spread across different GitHub issues.

**Comment by zaynehz** [comment]
I think #3 is a very important point to make and principle to follow - using wrangler should be as easy as possible and provide the best possible developer experience. JSON is more easily readable, more difficult to write incorrectly, and more familiar in the javascript ecosystem; ergo, a better developer experience. 

(Disclaimer: this comment is brought to you by a couple of hours of trying to debug an issue with wrangler that turned out to be two brackets in the wrong place in my TOML file)

**Comment by danielrs** [comment]
Agree that JSON is the most familiar to the JS ecosystem. Another good thing about JSON is that it's a subset of YAML, so any developers that want to use YAML can just convert it to JSON. On another note, I'm not sure what the official plans are but it would be nice to have some sort of modular configuration so different resources can be defined in "blocks", similar to what Kubernetes does with its resources type. This will allow us to:

- Define all the resources for a project in file
- Or define all resources in separate file
- Easier to automate or generate the files using templating tools
Just my two cents.

**Comment by ndisidore** [comment]
Sharing from an internal discussion:

Something like [cuelang](https://cuelang.org/) could be interesting.
It is pretty dang straightforward in the way its syntax works, supports typing, has built in validation, is scriptable, has a built in formatter (no need to worry about whitespace) and has transforms to accept json & yaml as both input or output (for multi style support) 
There are wasm builds for cuelang that could be used to integrate with wrangler.

However, it is a newer config language that has a bit of its own learning curve, and for that reason alone it may be more of a fun though experiment then something practical.

**Reply by petebacondarwin** [reply]
While Cue looks very interesting, I think the bigger driving force here is to make the configuration accessible to the majority of Workers developers, who are mostly used to the JS ecosystem, which is what gives JSON(C/5)/YAML a clear headstart.

**Comment by cmackenzie1** [comment]
Adding a concrete example to @zaynehz 's comment.

When referencing the docs for `wrangler.toml` many of the examples use the inline list syntax [^1] such as 

```toml
[[r2_buckets]]
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = '<YOUR_BUCKET_NAME>'
```

While writing workers with just a single top level environment this syntax is clear but once you add environments into the mix things become more confusing and less intuitive. For example

```toml
name = "default-environment"

[[r2_buckets]]
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = '<YOUR_BUCKET_NAME>'

[env.staging]
name = "staging-environment"

[[r2_buckets]] # this actually doesn't exist under `env.staging` prefix!
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = '<YOUR_BUCKET_NAME>'
```

We can see here that the intent it the second `[[r2_buckets]]` block is to be a part of the staging environment it actually ends up being a duplicated definition of the first `[[r2_buckets]]` block. 

There is a toml syntax for we can adopt in the docs to help make things clearer but the solution still isn't perfect. It involves not using the inline tables syntax. 

```toml
name = "default-environment"
r2_buckets = [
    { binding = 'MY_BUCKET' , bucket_name = '<YOUR_BUCKET_NAME>' }
]


[env.staging]
name = "staging-environment"
r2_buckets = [
    { binding = 'MY_BUCKET' , bucket_name = '<YOUR_BUCKET_NAME>' }
]
```


This confusion extends to the other developer platform products as well and not just R2. A non-exhaustive list is 
- `unsafe.bindings` 
- `durable_objects`
- `kv_namespaces`


Finally, I should note for those who prefer the inline syntax, the correct form is to use a fully-qualified keyname. 

```toml
[env.staging]
name = "staging-environment"

[[env.staging.r2_buckets]]
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = '<YOUR_BUCKET_NAME>'
```

[^1]: https://developers.cloudflare.com/r2/data-access/workers-api/workers-api-usage/
