### DISCUSSION TITLE
Continuous Integration

### DISCUSSION THREAD

**Discussion by vhscom** [cloudflare/workers-sdk#7834] [Q&A] [answered]
Trying to run my workers through a test workflow in CI using GitHub Actions with `ubuntu-latest` and [receive an error](https://github.com/vhscom/private-landing/actions/runs/12878620829/job/35904850230):
```
test/app.test.ts:
  
  # Unhandled error between tests
  -------------------------------
  error: Cannot find package 'cloudflare:test' from '/home/runner/work/private-landing/private-landing/test/app.test.ts'
  -------------------------------
```

My action looks like:
```yaml
name: CI

on: push

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: "https://npm.jsr.io"
          bun-version: canary

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

```

And the test failing:
```ts
import { SELF } from "cloudflare:test";
import { expect, it } from "vitest";

it("dispatches fetch event", async () => {
	const response = await SELF.fetch("https://example.com/index.html");
	expect(response.status).toBe(200);
	expect(await response.text()).toContain("<!doctype html>");
});
```

Which can be reproduced by cloning this template repository and attempting to run tests in a GitHub action workflow:
https://github.com/vhscom/private-landing/blob/main/test/sanity/fetch-integration-self.test.ts

Am I missing something obvious related to the ambient type declaration? Mine looks like:
```ts
declare module "cloudflare:test" {
	export * from "@cloudflare/workers-types/experimental";
	export * from "@cloudflare/vitest-pool-workers";
	export interface ProvidedEnv extends Env {}
}
```

Thanks in advance for any help anyone has!
