### ISSUE TITLE
🚀 Feature Request: Implement `config.dev.proxy` and/or  `config.dev.command`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workers-sdk#1180]
### Describe the solution

When using wrangler with frameworks like nextjs that come with their own development server, we'd like to be able to use one host for developing on it. This probably requires a combination of proxying a dev server through wrangler's dev server, and additionally being able to run a custom command during dev (_not_ `[build.command]`).

As an example, consider next.js (with ssg or csr, we don't support ssr with next js just yet). You currently have to run `next dev` in a separate terminal tab to the one you're running `wrangler dev` in (and in order; you have to first start up the worker, and then the next dev server). You also have to inject a global into your bundle that explicitly tells your app to make requests to `localhost:8787` during dev, and something else when you deploy. And finally, you have to do a separate build of the next app and use something like `--experimental-public` (or soon to be `--assets`) to deploy the site assets. It's all a bit fiddly, and we can do better. 

Ideally, we'd be able to setup `wrangler.toml` like so 

```toml
name = "my-worker"
main = "path/to/worker.js"
assets = "dist" # or wherever you set up `next build` to output

[dev]
command = "next dev" # this would override `[build.command]` during wrangler dev
proxy = "http://localhost:3000"

[build]
command = "next build"
``` 

- This would also work well with frameworks like remix that also generate the worker themselves. 
- Keen eyed folks will make a direct parallel with how Pages does this, which is quite clever; Pages can detect the port you're running and automatically setup the proxy and such. Maybe we don't want that magic, but maybe we do. 
- This also solves a longstanding problem we've had with not being able to run longrunning processes during dev with custom builds. those have always had to be one shot commands.
