### ISSUE TITLE
🚀 Feature Request: Automatically match up, or explicitly warn when not matching on, service binding environments

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#1607]
### Describe the solution

Right now, we match on just the name of the service. It might be useful to either require users to run Worker A in environment E if they have a binding on Worker B such as:

```toml
name = "B"

services = [
  { binding = "MY_BINDING", service = "A", environment = "E" }
]
```

Or at least, warn if A is running under some environment other than E.
