### ISSUE TITLE
🐛 BUG: Prod/release build on main seems to fail when multiple packages need releasing

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#1746]
### What version of `Wrangler` are you using?

wrangler@latest

### What operating system are you using?

GitHub

### Describe the Bug

https://github.com/cloudflare/wrangler2/runs/8073062908?check_suite_focus=true

**Comment by JacobMGEvans** [comment]
We should test if this is still an issue sometime.

**Comment by rozenmd** [comment]
It's still an issue sometimes 😬 

2/3 of our releases had to be re-run today

**Comment by JacobMGEvans** [comment]
@rozenmd Do you think it might have to do with the modify version script? Maybe when multiple releases happen Changeset expects monorepo behavior but that is usually through Lerna, Turborepo or the like... Instead the custom behavior we have disrupts something Changesets is doing in that time for the other packages. 
```
      - name: Modify package.json version
        run: node .github/version-script.js
```

**Comment by rozenmd** [comment]
I was looking at this:
```
      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.js
          publish: npx changeset publish
```

Why does `node .github/changeset-version.js` also do `npx changeset publish`? might be the issue here?

CC: @petebacondarwin

**Comment by rozenmd** [comment]
Compare to miniflare, a similar monorepo, which does:
```
      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
```
