### ISSUE TITLE
🐛 BUG: unstable_dev test runner does not pass custom build correctly to cmd on Windows

### ISSUE THREAD

**Issue by JustinGrote** [cloudflare/workers-sdk#2389]
### What version of `Wrangler` are you using?

2.6.0

### What operating system are you using?

Windows

### Describe the Bug

```toml
name = "denotest"
main = "out.js"
compatibility_date = "2022-12-08"
[build]
command = "deno bundle --unstable ./src/worker.ts out.js"
```

Custom build works fine with `wrangler publish --dry-run --outdir .`, however when running in a test runner, it wraps the argument in quotes, which fails in `cmd` on windows.

```typescript
const worker: UnstableDevWorker = await unstable_dev('./out.js', { logLevel: 'debug', local: true, config: 'wrangler.toml' }, { disableExperimentalWarning: true })
```

However with the test runner, it incorrectly encapsulates it in quotes when passing it to the shell, thus not being found in cmd. This happens even if I specify just a single command without arguments.

```
------- output -------
 ⛅️ wrangler 2.6.0 (update available 2.6.2)
-------------------------------------------
Running custom build: deno bundle --unstable ./src/worker.ts out.js
'\"deno bundle --unstable ./src/worker.ts out.js\"' is not recognized as an internal or external command,
operable program or batch file.
```

### Resolution
Dont quote when passing to cmd, also let me specify my own shell on windows such as `pwsh`
