### ISSUE TITLE
🐛 BUG: cloudflare/wrangler-action@2.0.0 fails to recognize branch

### ISSUE THREAD

**Issue by janithcooray** [cloudflare/workers-sdk#2569]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What version of `Wrangler` are you using?

2.0.0

### What operating system are you using?

Linux

### Describe the Bug

We’ve been using Wrangler CLI to deploy Cloudflare pages projects for more than 6 months now without a single issue.
we have over 35 pages projects with the exact same deployment strategy. this issue only occurred in 1 so far.

- there were no other open issues similar to this
- there were no format guidelines for issues so i wrote in my own format.

# BUG description 

we have more than 1 branch on each github repository containing pages source.  When we make a commit on a main branch, it gets deployed as a production build. when we make a commit on a branch other than main, it gets deployed as preview build. yesterday, we found that a commit made to non-production branch lead to a production build.

# Steps to reproduce (random occurrence)

1. Create a pages project
2. Create a repo on github and commit the following files to the main branch

- Create a basic html file under `app/public/index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Production Build</title>
</head>
<body>
    
</body>
</html>
```
- and the workflow file `.github/workflows/main.yml`
```
name: Deploy to Pages
on:
  push:
    branches: [ main, staging, dev/** ]
  pull_request:
    branches: [ staging ]

env:
  PROJECT_NAME: "<INSERT PAGES PROJECT NAME>"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3      
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.PAGES_DEPLOY_API }}
          accountId: ${{ secrets.PAGES_DEPLOY_ACCOUNT }}
          workingDirectory: 'app'
          command: pages publish public --project-name=${{ env.PROJECT_NAME }}
```
- (replace the project name to match the pages project and cloud credentials required by wrangler)

- github actions workflow will deploy the project to the pages account as a production build(takes a few seconds)

3. Checkout on a new branch (ex- named "staging") and make a simple change.
Checkout to a new branch and change the `Production Build` text in the html file to `Preview Build`

at this point, github actions workflow should deploy the project to the pages account as a preview build.

however, since yesterday preview builds are recognized as production build on the above deployment strategy within the cloudflare pages project

# Occurrence Frequency :
So far this only happened on 1 project, others with the same workflow did not have this bug.

# Environment Info
cloudflare/wrangler-action@2.0.0 on GitHub private repository
Runs on: Github actions - ubuntu-latest
