### ISSUE TITLE
🐛 BUG: wrangler dev fails with "Error while creating remote dev session:"

### ISSUE THREAD

**Issue by kjk** [cloudflare/workers-sdk#2581]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.8.0

### What operating system are you using?

Windows

### Describe the Bug

I run `wrangler dev` and get an error:
```
✘ [ERROR] Error while creating remote dev session: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

      at JSON.parse (<anonymous>)
      at parseJSON
  (C:\Users\kjk\src\filestore\upload\node_modules\wrangler\wrangler-dist\cli.js:117213:17)
      at createPreviewSession
  (C:\Users\kjk\src\filestore\upload\node_modules\wrangler\wrangler-dist\cli.js:125000:51)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async start
  (C:\Users\kjk\src\filestore\upload\node_modules\wrangler\wrangler-dist\cli.js:127410:9)
```

My `wrangler.toml`:

```toml
name = "upload"
main = "src/index.js"
compatibility_date = "2023-01-21"

# workers_dev = true
route = { pattern = "upload.filestore.dev", zone_id = "7aca111cc4dd5c8af033246fba8d4e43", custom_domain = true }

[[r2_buckets]]
binding = "FILESTORE_BUCKET"
bucket_name = "filestore"
preview_bucket_name = "filestore-dev"
```

This is the log of `workers dev --log-level debug >out.txt`:
[out.txt](https://github.com/cloudflare/wrangler2/files/10471531/out.txt)

The problem seems to be that it sends a request to `https://filestore.dev/cdn-cgi/workers/preview/?s0=Ac9OfirVWz-O8NoRieYPFBJeb1kY0nry0pWlzllc3Hs9ARA9u-JNX2nDDadmhTBDw71VOzB3LYTXmiS6t8QD2vo1kbzjMChWprIYZgefVgRyCT1YKh5GlWai5N-jZrj8MX-_UXTDe7mThfavIjAXshWlo6ovRB-YuOO97P6JLuK2aiuPlGT115YPivCTEPQkt1CoMaX08rA5wkqacQwc9ohpPuTRbFeHtbN7jfcz_hEFK-bY5raNQM-7NaS944xI8wkr502KSDqr9D0WPdUr5r7yK8M93eFvqjuoge_AILclpriDxvbjVWbjyaNkyLuK2w` but that returns an HTML page about "Invalid Workers Preview configuration" instead of (presumably) upload.filestore.dev (since my worker is configured to that custom domain).

The client should detect that error condition (getting HTML instead of JSON).

But also it should just work.
