### ISSUE TITLE
no polyfill for 'http' ?

### ISSUE THREAD

**Issue by touhidurrr** [cloudflare/workers-sdk#2617]
After requiring https://www.npmjs.com/package/mongodb-data-api on my app, I am getting the following errors:
![image](https://user-images.githubusercontent.com/46617994/204008221-f167f24b-9aab-4d2a-9608-d2862c2787e7.png)

I am using the **node_compat** mode.
I guess this is caused by **http** not polyfilled properly???
Can you guys kindly fix this issue?

Here is my wrangler.toml file:
```toml
compatibility_date = "2022-11-25"
account_id = "<ACCOUNT_ID>"

name = "<APP_NAME>"
workers_dev = true
node_compat = true
main = "src/index.js"
```
