### ISSUE TITLE
🐛 BUG: 'open a browser' shortcut opens custom domain, if present, in wrangler dev

### ISSUE THREAD

**Issue by KianNH** [cloudflare/workers-sdk#2691]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.9.1

### What operating system are you using?

MacOS

### Describe the Bug

When using a Worker that has a custom domain, the `open a browser` shortcut will open the custom domain (i.e `https://custom.example.com:8787`) which will timeout.

Repro:

`wrangler.toml`

```toml
name = "custom-repro"
main = "src/index.ts"
compatibility_date = "2023-02-08"

[route]
pattern = "custom.example.com"
custom_domain = true
```

Before the script is uploaded to the edge preview (before the `Total Upload` output), `b` will open `http://127.0.0.1:8787` as expected - after that, it will open your custom domain.
