### ISSUE TITLE
🐛 BUG: Cannot use host with local wrangler --experimental-local

### ISSUE THREAD

**Issue by tizmagik** [cloudflare/workers-sdk#2821]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12.0

### What operating system are you using?

Mac

### Describe the Bug

```
wrangler dev --node-compat --experimental-local --live-reload -e local
```

wrangler.toml

```toml
name = "worker"
main = "./src/index.ts"
compatibility_date = "2023-01-31"
account_id = "snip"
workers_dev = true

[dev]
port = 3000
host = "localhost:8787"

[env.local]
name = "local"
vars = { ENVIRONMENT = "dev" }
kv_namespaces = [
  { binding = "KV_BINDING", id="_", preview_id = "local" }
]
```

I get this error

```
 ⛅️ wrangler 2.12.0 
--------------------

✘ [ERROR] Could not find zone for localhost:8787
```

Apologies if this is actually not a bug and I just don't have the configuration correct. What's the proper way to run the Worker completely locally (with a local "upstream" host)?
