### ISSUE TITLE
🐛 BUG: workers.api.error.zone_not_found

### ISSUE THREAD

**Issue by uhthomas** [cloudflare/workers-sdk#2906]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.12.3

### What operating system are you using?

macOS

### Describe the Bug

```toml
[env.staging]
name = "redacted"
route = { custom_domain = true, pattern = "redacted.com" }
```

```
❯ wrangler publish -e staging
 ⛅️ wrangler 2.12.2 (update available 2.12.3)
-------------------------------------------------------
Total Upload: 9.60 KiB / gzip: 3.09 KiB
Uploaded redacted (2.07 sec)

✘ [ERROR] A request to the Cloudflare API (/accounts/redacted/workers/scripts/redacted/domains/changeset?replace_state=true) failed.

  workers.api.error.zone_not_found for "redacted.com" [code: 10083]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```
