### ISSUE TITLE
🐛 BUG: compatibility_flags ignored when [vars] come first in wrangler.toml

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/workers-sdk#2945]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12.0

### What operating system are you using?

Mac

### Describe the Bug

This works as expected:

```toml
name = "test"
main = "src/index.ts"
compatibility_date = "2023-03-08"

compatibility_flags = [ "nodejs_compat" ]

[vars]
MY_ENV_VAR = "foo"
```

This configuration...

```toml
name = "test"
main = "src/index.ts"
compatibility_date = "2023-03-08"

[vars]
MY_ENV_VAR = "foo"

compatibility_flags = [ "nodejs_compat" ]
```

...appears to ignore the `nodejs_compat` compatibility flag:

```bash
✘ [ERROR] Could not resolve "node:async_hooks"

    src/index.ts:1:34:
      1 │ import { AsyncLocalStorage } from "node:async_hooks";
        ╵                                   ~~~~~~~~~~~~~~~~~~

  The package "node:async_hooks" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file to enable Node compatibility.
```

The ordering here shouldn't matter...should it?
