### ISSUE TITLE
🐛 BUG: Not injecting D1 Database for 'DB' as this version of Miniflare only supports D1 beta bindings

### ISSUE THREAD

**Issue by probablykasper** [cloudflare/workers-sdk#3020]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

2.15.0

### What operating system are you using?

macOS

### Describe the Bug

When I run `miniflare --modules -w build/index.ts` I get this message :
```
Not injecting D1 Database for 'DB' as this version of Miniflare only supports D1 beta bindings. Upgrade Wrangler and/or Miniflare and try again.
```

My `wrangler.toml`:
```toml
name = "limey-custom-domains"
compatibility_date = "2023-03-14"
account_id = "<REDACTED>"
main = "build/index.ts"

compatibility_flags = [
	"streams_enable_constructors"
]

[vars]
ZONE_ID = "<REDACTED>"
WORKER_NAME = "limey-custom-domains"

[build]
command = "npm run build"

[[ d1_databases ]]
binding = "DB"
database_name = "limey"
database_id = "<REDACTED>"
```

Related:
- #2402 (That issue is about integration tests)
