### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by balindersingh** [cloudflare/workers-sdk#3056]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

2.15.1

### What operating system are you using?

 Image: ubuntu-22.04

### Describe the Bug

I have added continuous deployment for my cloudflare worker using github action.. but when github action tries to deploy it throws following error:

```
Using API Token authentication
 ⛅️ wrangler 2.15.1 
🌀 Creating the secret for the Worker "weblead-app" 

✘ [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts/weblead-app/secrets) failed.

  global variable REALM_APPID already set [code: 10053]
```

this is my github action looks like

```
on:
  push:
    branches:
      - master
      - ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_KEY }}
          # Your Cloudflare Account ID
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          # A new line deliminated string of environment variable names that should be configured as Worker secrets
          secrets: |
            REALM_APPID
            MONGODB_REALM_API_KEY
            SENDGRID_API_KEY
            SLACK_SUBPATH
          # The Wrangler command you wish to run. For example: "publish" - this will publish your Worker
          command: "publish"
        env:
          REALM_APPID: ${{ secrets.GH_REALM_APPID }}
          MONGODB_REALM_API_KEY: ${{ secrets.GH_MONGODB_REALM_API_KEY }}
          SENDGRID_API_KEY: ${{ secrets.GH_SENDGRID_API_KEY }}
          SLACK_SUBPATH: ${{ vars.SLACK_SUBPATH }}


```
