### ISSUE TITLE
🐛 BUG: Producer Worker cannot be published after changing the service name of a tail_consumer

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/workers-sdk#3367]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Mac

### Describe the Bug

Following [these docs](https://developers.cloudflare.com/workers/platform/tail-workers/).

### Steps to reproduce

1. Create a hello world producer worker, with the following `wrangler.toml`

```toml
name = "tail-workers-test"
main = "src/index.ts"
compatibility_date = "2023-05-30"

tail_consumers = [{service = "tail-workers-test"}]
```

2. Publish the worker using `wrangler publish`
3. Observe that the Worker can be successfully published, and works
4. Change the service name from `tail-workers-test` to anything else (ex: `tail-workers-test-consumer`)
5. Run `wrangler publish` again, and observe the following error:

```
✘ [ERROR] A request to the Cloudflare API (/accounts/<ID>/workers/scripts/tail-workers-test) failed.

  workers.api.error.script_not_found [code: 10007]
```
