### ISSUE TITLE
🐛 BUG: No such table

### ISSUE THREAD

**Issue by Yanren1225** [cloudflare/workers-sdk#3479]
### Which Cloudflare product(s) does this pertain to?

D1, Workers/Other, Wrangler

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

Windows 11

### Describe the Bug

I've written a simple Workers script locally to get some data from D1

```ts
import { Router } from 'itty-router';

const router = Router();

export interface Env {
	kirbyDB: D1Database;
}

router.get('/kirby', async (_, env: Env) => {
	const { results } = await env.kirbyDB.prepare('SELECT * FROM game').all();
	console.log(results);
	return new Response('kirby');
});

export default {
	fetch: router.handle,
};
```

In `wrangler.toml` I bind it like this

```toml
name = "learn-workers"
main = "src/worker.ts"
compatibility_date = "2023-06-15"

[[d1_databases]]
binding = "kirbyDB"
database_name = "kirby"
database_id = "7d96fcb0-da44-4d95-ae22-8fd7101e7045"
```

In the Cloudflare Dashboard above I set up the database like this

![图片](https://github.com/cloudflare/workers-sdk/assets/25337480/4b1bd848-329f-44c9-a397-b4aa88b6134c)

I think the database should be fine, because I can access it using wrangler

```shell
❯ wrangler d1 execute kirby --command "SELECT * FROM game"

🌀 Mapping SQL input into an array of statements
🌀 Parsing 1 statements
🌀 Executing on kirby (7d96fcb0-da44-4d95-ae22-8fd7101e7045):
🚣 Executed 1 commands in 4.9073589984327555ms
┌─────────┐
│ console │
├─────────┤
│ gba     │
├─────────┤
│ sfc     │
└─────────┘
```

But in the script I get this error

```shell
[mf:err] Cause: Error: Error: SqliteError: no such table: game  
```

Did I make a mistake or something?
