### ISSUE TITLE
🐛 BUG: Invalid compatibility date: 2023–06–28

### ISSUE THREAD

**Issue by EmilyYond** [cloudflare/workers-sdk#3543]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.1

### What operating system are you using?

Mac

### Describe the Bug

I am following these docs https://nitro.unjs.io/deploy/providers/cloudflare to deploy my nuxt 3 SSR site and I am encountering this error on my github action:

![Screenshot 2023-06-29 at 15 37 36](https://github.com/cloudflare/workers-sdk/assets/128067060/a8cfbdb4-89da-45d3-b076-325156cca891)

Does anyone know what might be causing this?

My wrangler.toml:

```
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2023–06–28"
account_id = "a181d74bf534ed4dae86272a432541f4"
[site]
bucket = ".output/public"
```

And my cloudflare.yml
```
name: cloudflare

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@master

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build
        run: yarn build
        env:
          NITRO_PRESET: cloudflare

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --name my-project
```
