### ISSUE TITLE
🐛 BUG: ERROR: Must specify a directory.

### ISSUE THREAD

**Issue by arnonrdp** [cloudflare/workers-sdk#3706]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms, Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

Latest

### What version of Node are you using?

18.16.1

### What operating system are you using?

Mac

### Describe the Bug

Guys, I'm getting this error (**Must specify a directory**) when running a GitHub Action in order to Deploy a repository on CloudFlare Worker.

In the documentation, I didn't find anything regarding specifying a directory.

Could someone tell me where and how I report this?

---

This is my `wrangler.toml`:
```toml
name = "sparkling-paper-3924"
main = "src/worker.js"
compatibility_date = "2023-08-01"
account_id = "febb3b25d5ad9fea8d9db175fe2c3477"
```

This is my `.github/workflows/deploy.yml`:
```yml
name: Deploy to Cloudflare

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Deploy
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name=sparkling-paper-3924

```

### Please provide a link to a minimal reproduction

https://github.com/globe-and-citizen/sparkling-paper-3924

### Please provide any relevant error logs

<img width="1272" alt="Captura de Tela 2023-08-03 às 15 55 18" src="https://github.com/cloudflare/workers-sdk/assets/26576201/10ce49e1-c9a1-4842-b5b0-3b0ad8bb6499">
