### ISSUE TITLE
🐛 BUG: Uncaught TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Skye-31** [cloudflare/workers-sdk#3738]
### Which Cloudflare product(s) does this pertain to?

Wrangler core, Other

### What version(s) of the tool(s) are you using?

Wrangler 3.5.0

### What version of Node are you using?

18.17.0

### What operating system are you using?

Mac

### Describe the Bug

When creating a worker that defines a Durable Object (but doesn't export it in the main file), a very cryptic error is thrown
```
service core:user:my-worker: Uncaught TypeError: Class extends value undefined is not a constructor or null
  at index.js:1648:44 in maskDurableObjectDefinition
  at index.js:1657:26
✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

We should probably check whether the main script exports the DO, and if it doesn't, provide an easier to understand error. 

### Please provide a link to a minimal reproduction

```ts
export default {}
// note, the lack of `export class MyDO`
```
```toml
name = "my-worker"
script = "src/index.ts"
compatibility_date = "2023-08-11"

[[durable_objects.bindings]]
name = "MY_DO"
class_name = "MyDO"

[[migrations]]
tag = "v1"
new_classes = ["MyDo"]
```
