### ISSUE TITLE
🐛 BUG: HYPERDRIVE binding is returning as `undefined` on the `env` worker param

### ISSUE THREAD

**Issue by drewdecarme** [cloudflare/workers-sdk#4133]
### Which Cloudflare product(s) does this pertain to?

Hyperdrive

### What version(s) of the tool(s) are you using?

3.11.0 [Wrangler]

### What version of Node are you using?

18.14.0

### What operating system are you using?

Mac

### Describe the Bug

The Hyperdrive binding is being returned as `undefined`. I've done the below steps.
- Created a DB via neon
- Created the hyperdrive config via the wrangler CLI
- Added the ID via the bindings in my `wrangler.toml`
```toml
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "hyperdrive_id_via_wrangler"
```
- Logged out the environment as well and am only getting the variables that I have defined directly in the `wrangler.toml`. In addition none of the secrets that I have added have actually registered. I had to use a `.dev.vars` file in order to get some secrets to take. I'm unsure if this is wrangler or there is something else outstanding that I'm missing.

### Please provide any relevant error logs

logging out the `env` only outputs the variables defined in the `wrangler.toml` and in the `.dev.vars` file.

```
 ⛅️ wrangler 3.11.0
-------------------
▲ [WARNING] Processing wrangler.toml configuration:

    - Hyperdrive Bindings are currently in beta to allow the API to evolve before general
  availability.
      Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose`


▲ [WARNING] Enabling Node.js compatibility mode for built-ins and globals. This is experimental and has serious tradeoffs. Please see https://github.com/ionic-team/rollup-plugin-node-polyfills/ for more details.


Using vars defined in .dev.vars
Your worker has access to the following bindings:
- Hyperdrive Configs:
  - HYPERDRIVE: <hyperdrive_id_from_config>
- Vars:
  - API_AUTH0_DOMAIN: "__REDACTED__"
  - API_AUTH0_CLIENT_ID: "__REDACTED__"
  - API_AUTH0_CLIENT_AUDIENCE: "__REDACTED__"
  - DATABASE_URL: "(hidden)"
  - DIRECT_URL: "(hidden)"
```

**Comment by rozenmd** [comment]
Could you paste your wrangler.toml @drewdecarme ?

**Comment by drewdecarme** [comment]
Certainly. I've redacted a few of the variables.

```toml
name = "shank-city"
main = "src/index.ts"
compatibility_date = "2023-09-22"
node_compat = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "<GENERATED_FROM_WRANGLER>"

[vars]
API_AUTH0_DOMAIN = "__REDACTED__"
API_AUTH0_CLIENT_ID = "__REDACTED__"
API_AUTH0_CLIENT_AUDIENCE = "__REDACTED__"
LOG_LEVEL = "debug"
LOG_TYPE = "simple"
```
