### ISSUE TITLE
🐛 BUG: [Deploy Error] Uncaught TypeError: i2 is not a function  at worker.js:25074:16

### ISSUE THREAD

**Issue by souravdutt** [cloudflare/workers-sdk#4344]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

3.15.0

### What version of Node are you using?

18.18.2

### What operating system are you using?

ubuntu-latest (github actions), Windows (for direct local deployment)

### Describe the Bug

I am trying to deploy my Nuxt 3 app with cloudflare workers, using `wrangler deploy` command (also tried `npx wrangler deploy`) using both direct deplyment through my VS Code and through Github Actions. But getting the below error in logs:

```
Uncaught TypeError: i2 is not a function
    at worker.js:25074:16
    at worker.js:25076:6
    at worker.js:33063:4
    at worker.js:33064:3
   [code: 10021]
```

For more here is my Github Workflow (I am using Global API Key and Email for Authentication as I am unable to find out which Permissions does github action requires for my Cloudflare API Token.):
```
name: cloudflare

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@master

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ubuntu-latest-node-v18-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build
        run: yarn build
        env:
          NITRO_PRESET: cloudflare
          NUXT_SSR: 'true'
          
      - name: Install Wrangler
        run: npm uninstall -g @cloudflare/wrangler && npm install -g wrangler
      
      - name: Publish to Cloudflare
        run: wrangler deploy
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CF_API_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CF_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
```

### Please provide any relevant error logs

```
...
...
✘ [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts/my-nuxt-app) failed.

  Uncaught TypeError: i2 is not a function
    at worker.js:25074:16
    at worker.js:25076:6
    at worker.js:33063:4
    at worker.js:33064:3
   [code: 10021]

  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose


Error: Process completed with exit code 1.
```
