### ISSUE TITLE
🚀 Feature Request: Single Command to Apply Migrations to All D1 Databases in Wrangler

### ISSUE THREAD

**Issue by sugar-cat7** [cloudflare/workers-sdk#4471]
### Describe the solution

I'm currently working with multiple D1 databases in a Cloudflare Workers project and facing a workflow challenge. My `wrangler.toml` file defines numerous D1 database bindings, as shown below:

```toml
# Example wrangler.toml configuration
[[d1_databases]]
binding = "Test1"
database_name = "test-1"

[[d1_databases]]
binding = "Test2"
database_name = "test-2"

# ... additional configurations ...
```

Currently, to apply migrations, I need to execute `wrangler d1 migrations apply <database_name>` individually for each database. This process is manageable but becomes cumbersome, especially when integrated into CI workflows.

A potential command might look like `wrangler d1 migrations apply --all`, automatically detecting and applying migrations to each database defined in wrangler.toml.

This feature would significantly improve the developer experience and efficiency for projects utilizing Cloudflare's D1 databases with Workers.
