### ISSUE TITLE
🚀 Feature Request: `wrangler types` to include send_email bindings

### ISSUE THREAD

**Issue by jonasb** [cloudflare/workers-sdk#4569]
### Describe the solution

After adding this to `wrangler.toml` I expect `wrangler types` to include the `NOTIFICATION_EMAIL` binding, but it doesn't.

```toml
[[send_email]]
type = "send_email"
name = "NOTIFICATION_EMAIL"
```
