### ISSUE TITLE
🐛 BUG:   spawn /bin/sh ENOENT (Fedora Linux)

### ISSUE THREAD

**Issue by widiu7omo** [cloudflare/workers-sdk#4731]
### Which Cloudflare product(s) does this pertain to?

Pages, Workers for Platforms, Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.22.3

### What version of Node are you using?

20.10.0

### What operating system are you using?

Linux (Fedora)

### Describe the Bug

Error below when running with pnpm dev.

 ⛅️ wrangler 3.22.3
-------------------
Running custom build: pnpm run build

✘ [ERROR] Command failed with ENOENT: pnpm run build

  spawn /bin/sh ENOENT
  
  
Here is my wrangler.toml
  
```toml 
name = "hono-react-ssr"
main = "server.ts"
compatibility_date = "2023-09-20"

[site]
bucket = "dist"

[build]
command = "pnpm run build"
cwd = "dist"
watch_dir = "src"

```

### Please provide any relevant error logs

pnpm dev

> hono-vite@0.0.0 dev /home/dio/playground/sandbox/hono-react-cloudflare
> wrangler dev

 ⛅️ wrangler 3.22.3
-------------------
Running custom build: pnpm run build

✘ [ERROR] Command failed with ENOENT: pnpm run build

  spawn /bin/sh ENOENT

If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
