### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by coreybutler** [cloudflare/workers-sdk#4948]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.27.0

### What version of Node are you using?

20.7.0

### What operating system and version are you using?

Windows 11

### Observed behavior
Running `npx wrangler d1 execute high_availability --local --file=./data_model/update.sql` fails whereas `npx wrangler d1 execute high_availability --file=./data_model/update.sql` succeeds.

<img width="734" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/770982/61bdd7e7-1a8b-4d51-a9cd-05e5e14d5665">

For reference, the `update.sql` script contains:

```sql
ALTER TABLE cluster
ADD COLUMN pubsub_topic_id TEXT;
```

The `wrangler.toml` consists of:

```toml
name = "my-project"
main = "src/index.js"
compatibility_date = "2023-11-20"

[env.dev.vars]
ORIGIN = "http://localhost:8787"

[[env.dev.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "high_availability"
database_id = "REDACTED"

[env.production.vars]
ORIGIN = "https://mydomain.com"

[[env.production.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "high_availability"
database_id = "REDACTED"

# This section exists so local development will identify the DB
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "high_availability"
database_id = "REDACTED"
```
_The `database_id` is the same on all entries._

### Expected behavior
The local update should work as it does on the remote server.

### Steps to reproduce
To reproduce, create any DB using `npx wrangler d1 execute mydb --local --file=./my_ddl.sql`. Then add a column using `npx wrangler d1 execute mydb --local --file=./update.sql`

_my_ddl.sql_
```sql
CREATE TABLE IF NOT EXISTS tbl
(
  id TEXT NOT NULL,
  nm TEXT NOT NULL
  CONSTRAINT PK_tbl PRIMARY KEY (id)
)
;

CREATE UNIQUE INDEX IF NOT EXISTS unique_id_idx
  ON tbl (id)
;
```

_update.sql_
```sql
ALTER TABLE tbl
ADD COLUMN example TEXT;
```

### Please provide any relevant error logs

```sh

--- 2024-02-07T18:28:16.380Z debug
🪵  Writing logs to "___\.wrangler\logs\wrangler-2024-02-07_18-28-14_717.log"
---

--- 2024-02-07T18:28:16.380Z debug
Failed to load .env file ".env": Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at tryLoadDotEnv (___\api\node_modules\wrangler\wrangler-dist\cli.js:124313:72)
    at loadDotEnv (___\api\node_modules\wrangler\wrangler-dist\cli.js:124322:12)
    at ___\api\node_modules\wrangler\wrangler-dist\cli.js:162622:20
    at ___\api\node_modules\wrangler\wrangler-dist\cli.js:131240:16
    at maybeAsyncResult (___\api\node_modules\wrangler\wrangler-dist\cli.js:129461:44)
    at ___\api\node_modules\wrangler\wrangler-dist\cli.js:131239:14
    at ___\api\node_modules\wrangler\wrangler-dist\cli.js:129448:22
    at Array.reduce (<anonymous>) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '.env'
}
---

--- 2024-02-07T18:28:16.386Z log
🌀 Mapping SQL input into an array of statements
---

--- 2024-02-07T18:28:16.388Z log
🌀 Executing on local database high_availability (3a1ea513-4fc5-xxxx-xxxxxxxxxxxxx) from .wrangler\state\v3\d1:
---

--- 2024-02-07T18:28:17.371Z log

---

--- 2024-02-07T18:28:17.492Z error
[31mX [41;31m[[41;97mERROR[41;31m][0m [1mA prepared SQL statement must contain only one statement.[0m


---

--- 2024-02-07T18:28:17.494Z log
[32mIf you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose[0m
---
```
