### ISSUE TITLE
🐛 BUG: `wrangler types` generates wrong types with dashes in vars, bindings, etc.

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#5090]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.29.0

### What version of Node are you using?

20.11.1

### What operating system and version are you using?

Windows

### Observed behavior
With the following config:
```toml
[vars]
some-var = "foobar"
```

The generated types file includes:
```typescript
interface Env {
	some-var: "foobar";
}
```

This is syntactically invalid.

### Expected behavior

This should wrap all keys in quotes:
```typescript
interface Env {
	"some-var": "foobar";
}
```

**Comment by Cherry** [comment]
More fun things that are technically valid:
```toml
[[kv_namespaces]]
id = "test-namespace"
binding = "🔒"

[vars]
"😀"="smiling"
"["="bracket"
"{"="curly"
"("="paren"
```
