### ISSUE TITLE
 🐛 BUG: Wrangler does not bind (Service Binding) correctly on localhost 

### ISSUE THREAD

**Issue by omarkhairy21** [cloudflare/workers-sdk#5232]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core, Miniflare

### What version(s) of the tool(s) are you using?

3.32.0

### What version of Node are you using?

20.9.0

### What operating system and version are you using?

Windows 11

### Observed behavior
I added a service binding called auth_service it gets recognized by Wrangler on Bootstrap however on the running time it does not get recognized 

![image](https://github.com/cloudflare/workers-sdk/assets/30784772/510211b9-1e54-446e-b321-93e823315630)

Here is the console log for env:
![image](https://github.com/cloudflare/workers-sdk/assets/30784772/42241544-7859-4fab-985e-f6aefae56502)

### Expected behavior
The Service binding gets recognized on run time too and works correctly 

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
```toml
main = "src/index.ts"
account_id = "account-id"
compatibility_date = "2023-02-19"
node_compat = true

[env.development]
name = "example-staging"
route = "test.example.io/*"

[[env.development.queues.producers]]
  queue = "some_queue"
  binding = "QUEUE"

[[env.development.queues.consumers]]
  queue = "some_queue"
  max_batch_size = 1
  max_batch_timeout = 1
  max_retries = 2

[env.development.durable_objects]
bindings = [
  { name = "ASSETS_PROCESSING", class_name = "AssetsProcessing"  }
]

[[env.development.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "db"
database_id = "some_id"

[env.development.vars]
ENVIRONMENT = "development"
service_id = "17"

[[env.development.services]]
binding="auth_service"
service="authenticationservice-staging"
```
- Commands used to start your local dev server, including custom env and cli args
```bash
wrangler dev --env development
```
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.
