### ISSUE TITLE
🐛 BUG: dispatch namespace bindings not present in local dev

### ISSUE THREAD

**Issue by matthewdavidrodgers** [cloudflare/workers-sdk#5497]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

3.45.0

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

Ubuntu 22.04.4 LTS 

### Observed behavior
When a dispatch namespace binding is present:
- `wrangler dev --remote` includes the binding on the `env`
- `wrangler dev` _does not_ include the binding on the `env`

### Expected behavior
When a dispatch namespace binding is present:
- `wrangler dev --remote` includes the binding on the `env`
- `wrangler dev` includes the binding on the `env`

### Steps to reproduce

```
npx wrangler dispatch-namespace create sample-namespace
```

```toml
# wrangler.toml
name="sample-dispatcher-worker"
compatability_date="2024-04-02"
main="index.js"

[[dispatch_namespaces]]
binding="dispatcher"
namespace="sample-namespace"
```

```javascript
// index.js
export default {
  async fetch(req, env) {
    console.log(`dispatcher included in env: ${'dispatcher' in env}`);
    return new Response();
  }
}
```

With the above project - run `wrangler dev` in both local and remote modes and observe the binding missing in local dev
