### ISSUE TITLE
🐛 BUG: Service binding RPC fails between  local servers with & without --remote flag

### ISSUE THREAD

**Issue by tsoumdoa** [cloudflare/workers-sdk#5650]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core, Miniflare, Other

### What version(s) of the tool(s) are you using?

wrangler 3.51.0

### What operating system and version are you using?

Mac 14.4.1

### Observed behaviour
A worker, say worker-A, fails to find worker-B when worker-A is configured to use worker-B for service-binding via RPC when worker-B is running on the local server with --remote flag, while worker-A runs without the --remote flag since this would try to find worker-B in the deployment. It's necessary for worker-A to run with --remote flag since it uses durable object and can't test the whole functionality without the flag.

### Expected behavior
worker-A connects with the worker-B and run the function as expected. It does run as expected when both of them are running without --remote flag, so the configuration and code I have should be all correct. 

### Steps to reproduce
Please note that the code below does not require --remote flag in reality, but it's a simplified version of the code for the demonstration purpose only. 
#### worker-A
**worker-a/package.json** 
``` json
{
  "name": "worker-a",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "deploy": "wrangler deploy",
    "dev": "wrangler dev",
    "start": "wrangler dev",
		"build": "wrangler deploy",
    "test": "vitest"
  },
  "devDependencies": {
    "@cloudflare/vitest-pool-workers": "^0.1.0",
    "@cloudflare/workers-types": "^4.20240405.0",
    "typescript": "^5.0.4",
    "vitest": "1.3.0",
    "wrangler": "^3.0.0"
  },
  "dependencies": {
		"screenshot-worker": "workspace:*",
    "hono": "^4.2.3"
  }
}
```

**worker-a/wrangler.toml**
```toml
#:schema node_modules/wrangler/config-schema.json
name = "worker-a"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

services = [
  { binding = "WORKER_B", service = "worker-b" }
]

```
**worker-a/index.js** 
``` js
export default {
  async fetch(request, env) {
    const result = await env.WORKER_B.add(1, 2);
    return new Response(result);
  }
}
```

#### worker-B
**worker-a/package.json** 
``` json
{
  "name": "worker-b",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "deploy": "wrangler deploy ",
    "dev": "wrangler dev --remote",
    "start": "wrangler dev",
		"build": "wrangler deploy",
    "test": "vitest"
  },
  "devDependencies": {
    "@cloudflare/vitest-pool-workers": "^0.1.0",
    "@cloudflare/workers-types": "^4.20240405.0",
    "typescript": "^5.0.4",
    "vitest": "1.3.0",
    "wrangler": "^3.0.0"
  },
  "dependencies": {
		"screenshot-worker": "workspace:*",
    "hono": "^4.2.3"
  }
}
```

**worker-b/wrangler.toml**
```toml
#:schema node_modules/wrangler/config-schema.json
name = "worker-b"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
[dev]
port = 8080
```

**worker-b/index.js** 
``` js
import { WorkerEntrypoint } from "cloudflare:workers";

export class WorkerB extends WorkerEntrypoint {
  async add(a, b) { return a + b; }
}
```

At each directories, run 
``` pnpm run dev ``` or  ```wrangler dev``` for ***worker-a*** and ```wrangler dev --remote``` for ***worker-b***. 

### Please provide any relevant error logs

[wrangler:err] Error: Cannot access `run` as we couldn't find a `wrangler dev` session for service "worker-b" to proxy to.
