### ISSUE TITLE
🚀 Feature Request: Warn if unexpected key is in the toml

### ISSUE THREAD

**Issue by Ankcorn** [cloudflare/workers-sdk#5681]
### Describe the solution

On more than one occasion I have been on a call with a user confused at why something from their wrangler toml is not applying correctly. 

They have been appending some config, often recommended by some docs, or a guide. To their `wrangler.toml` and are confused that the resource is not created.

```toml
[[kv_namespaces]]
binding = "KV"
id = "<NAMESPACE_ID>"

tail_consumer = [{ ... }]
```

On `wrangler deploy` it ignores the additional key in the kv_namespaces array and deploys the worker

It would be better if when running `wrangler deploy` the extension raised warnings whilst deploying.

```bash
Warning: Unexpected Key: tail_consumer is not a valid key for kv_namespaces.
```

The deployment should still succeed to avoid this being a breaking change.
