### ISSUE TITLE
🐛 BUG: No such module "__STATIC_CONTENT_MANIFEST".

### ISSUE THREAD

**Issue by DallasHoff** [cloudflare/workers-sdk#5899]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.57.1 [wrangler]

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

Mac Sonoma 14.2.1

### Observed behavior

I am attempting to deploy a Worker built with Nitro. When running `wrangler deploy`, I get the following output:

```
 ⛅️ wrangler 3.57.1
-------------------
Your worker has access to the following bindings:
- D1 Databases:
  - [...]
Total Upload: 560.33 KiB / gzip: 116.05 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/[...]/workers/scripts/[...]) failed.

  Uncaught Error: No such module "__STATIC_CONTENT_MANIFEST".
    imported from "index.js"
   [code: 10021]
```

From what I am reading in other issues, "__STATIC_CONTENT_MANIFEST" should be present in the deployment environment, but this error indicates it is not?

### Steps to reproduce

Deploy command: `wrangler deploy --env map`

wrangler.toml:

```toml
name = "..."
main = "./.output/server/index.mjs"
workers_dev = false
compatibility_date = "2024-05-22"

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"] },
]

[env.map]

routes = [
  { pattern = "...", custom_domain = true },
]

d1_databases = [
  { binding = "...", database_name = "...", database_id = "..." },
]
```

built index.mjs:
```js
globalThis._importMeta_={url:"file:///_entry.js",env:{}};export{a as default}from"./chunks/runtime.mjs";import"__STATIC_CONTENT_MANIFEST";
//# sourceMappingURL=index.mjs.map
```

My API has no site/static assets, only JavaScript files.

**Comment by penalosa** [comment]
You'll need to add the following snippet to your `wrangler.toml` file:

```toml
[site]
bucket = ".output/public"
```

(See the Nitro docs for more info: https://nitro.unjs.io/deploy/providers/cloudflare#cloudflare-module-workers)

This should work, but to note, we generally recommend using Cloudflare Pages to deploy Nitro apps: https://nitro.unjs.io/deploy/providers/cloudflare#cloudflare-pages
