### ISSUE TITLE
🐛 BUG: wrangler should fail if secrets put is used in a pages project

### ISSUE THREAD

**Issue by divyenduz** [cloudflare/workers-sdk#6217]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.57.1

### What version of Node are you using?

v18.18.1

### What operating system and version are you using?

Mac Sonoma 14.5 (23F79)

### Observed behavior
`wrangler secret put API_KEY` in a pages project creates a worker and puts the secret in the worker.

### Expected behavior
Either the `wrangler secret put API_KEY` command should create the secret in the relevant pages project or fail. Creating a new worker is incorrect. 

### Steps to reproduce
Please provide the following:
- `wrangler.toml`

```toml
name = "<project name>"
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

compatibility_flags = [ "nodejs_compat" ]
```

- run `npx wrangler secret put API_KEY`, this command succeeds but it should fail in a pages project. This command creates a brand new works and puts the secret there. This is not intuitive. 

Here is the internal discord chat with the related context: https://discord.com/channels/595317990191398933/799437470004412476/1258446892564484218
