### ISSUE TITLE
🐛 BUG: `--from-dash` doesn't know about the shape of all bindings

### ISSUE THREAD

**Issue by KianNH** [cloudflare/workers-sdk#6735]
### Which Cloudflare product(s) does this pertain to?

C3 (npm create cloudflare), Wrangler

### What version(s) of the tool(s) are you using?

3.78.3 [Wrangler], 2.27.0 [C3]

### What version of Node are you using?

22.6.0

### What operating system and version are you using?

macOS 14.6.1

### Describe the Bug

When using `--existing-script` in C3 or `--from-dash` in Wrangler, Queue bindings are shown in Wrangler.toml as their `unsafe` shape.

```toml
[unsafe]
  [[unsafe.bindings]]
  name = "QUEUE"
  queue_name = "docs-v2-test"
  type = "queue"
```

It looks like Queues is missing from the below `switch` statement:

https://github.com/cloudflare/workers-sdk/blob/e4fe35cc52c3eb01dfb81fd44c83397f06db4597/packages/wrangler/src/init.ts#L1017-L1181
