### ISSUE TITLE
🐛 BUG: Improve node_compat = true warning

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/workers-sdk#6759]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.78.5

### What version of Node are you using?

22.3

### What operating system and version are you using?

Mac Sonoma 14.6.1

### Describe the Bug

With the following `wrangler.toml`

```toml
name = "node-compat-warning"
main = "src/index.js"
compatibility_date = "2024-09-09"
node_compat = true
```

And a basic hello world Worker, I see the following error message when I run `wrangler dev`

```
▲ [WARNING] Enabling Wrangler compile-time Node.js compatibility polyfill mode for builtins and globals. This is experimental and has serious tradeoffs.
```

This warning doesn't tell you what you _should_ do instead — to enable `nodejs_compat_v2` (soon, `nodejs_compat`) And I think we have an opportunity to link to these docs from this error:

https://developers.cloudflare.com/workers/runtime-apis/nodejs/

`node_compat = true` is effectively "old way" and deprecated. We should message as such.
