### ISSUE TITLE
🐛 BUG: `[alias]` no longer working in `wrangler dev` in v3.80.0

### ISSUE THREAD

**Issue by mhart** [cloudflare/workers-sdk#6898]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.80.0

### What operating system and version are you using?

Mac Sonoma 14.6.1

### Describe the Bug

The following works fine in v3.79.0:
```toml
[alias]
"critters" = "./my-shim.mjs"
"@opentelemetry/api" = "./my-shim.mjs"
```

But in v3.80.0 it errors in `wrangler dev` as if the aliases have no effect:

```
✘ [ERROR] Could not resolve "critters"
# etc...
```
