### ISSUE TITLE
🚀 Feature Request: `wrangler types` should use union types for possible values

### ISSUE THREAD

**Issue by luisrudge** [cloudflare/workers-sdk#6931]
## `wrangler.toml`

```toml
[vars]
SEND_EMAILS_ENABLED = "false"

[env.preview.vars]
SEND_EMAILS_ENABLED = "true"

[env.production.vars]
SEND_EMAILS_ENABLED = "true"
```

when I run `wrangler types`, it creates this interface:

```typescript
interface Env {
	SEND_EMAILS_ENABLED: "false";
}
```

which causes a type error because the type is not `'false' | 'true'` or even `string`.
<img width="963" alt="image" src="https://github.com/user-attachments/assets/30e4c1e4-86a9-4bfb-a7a8-0f588ffbb026">

So the values need to be generated with all the possible values, and not with only the local value.
