### ISSUE TITLE
🐛 BUG: `observability` was unexpected

### ISSUE THREAD

**Issue by weslenng** [cloudflare/workers-sdk#7079]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.82.0

### What operating system and version are you using?

Windows 11

### Observed behavior
Even Better TOML extension for VSCode highlight an error if I set `observability` settings

### Expected behavior
I think the error highlight is a false-positive and the problem is in the `wrangler/config-schema.json` file

### Steps to reproduce
Please provide the following:
- A minimal working subset of your `wrangler.toml`

```toml
#:schema node_modules/wrangler/config-schema.json
[observability]
enabled = true
head_sampling_rate = 1
```

![image](https://github.com/user-attachments/assets/83052e02-707e-439c-9369-689a1464c614)
