### ISSUE TITLE
🐛 BUG: Attempting to run wrangler dev on docker container, port reloading and not forwarded correctly

### ISSUE THREAD

**Issue by samhren** [cloudflare/workers-sdk#7196]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler

### What version(s) of the tool(s) are you using?

3.85.0 [Wrangler]

### What version of Node are you using?

Bun 1.1.34

### What operating system and version are you using?

Mac Sequoia 15.0

### Observed behavior
After running docker-compose, this is the result I see:

```
weddle-migrated-worker-old-1  | 
weddle-migrated-worker-old-1  |  ⛅️ wrangler 3.85.0
weddle-migrated-worker-old-1  | -------------------
weddle-migrated-worker-old-1  | 
weddle-migrated-worker-old-1  | 
weddle-migrated-worker-old-1  | Your worker has access to the following bindings:
weddle-migrated-worker-old-1  | - D1 Databases:
weddle-migrated-worker-old-1  |   - DB: weddle-solutions (...) (local)
weddle-migrated-worker-old-1  | ⎔ Starting local server...
weddle-migrated-worker-old-1  | [wrangler:inf] Ready on http://localhost:8787
weddle-migrated-worker-old-1  | [wrangler:inf] Updated and ready on http://localhost:38291
weddle-migrated-worker-old-1  | ⎔ Reloading local server...
```

I then attempt to visit localhost:8787 and I receive:

**This page isn’t working
localhost didn’t send any data.**

Here is my docker-compose.yml:

```YAML
version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  
  worker-old:
    build:
      context: ./worker-old
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./worker-old:/app
      - /app/node_modules
    environment:
      - SECRET_KEY=${SECRET_KEY}
```

Here is my ./worker-old/Dockerfile:

```Dockerfile
FROM oven/bun:1.1-debian
WORKDIR /app
COPY package*.json bun.lockb ./
RUN bun install
COPY . .
EXPOSE 8787
CMD ["bun", "run", "dev"]
```

### Expected behavior

**I should be able to see and view the response my cloudflare worker is sending on the development branch.** 

When run locally (bun run dev in ./worker-old) this is the response I see:

```
$ wrangler dev

 ⛅️ wrangler 3.85.0
-------------------

Your worker has access to the following bindings:
- D1 Databases:
  - DB: weddle-solutions (53f3e058-d824-4289-b7ac-52a2e85fa547) (local)
⎔ Starting local server...
[wrangler:inf] Ready on http://localhost:8787
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│  [b] open a browser, [d] open devtools, [l] turn off local mode, [c] clear console, [x] to exit
```

The port and everything works as expected.

### Steps to reproduce
Please provide the following:
- Created docker-compose.yml as above
- Run `bun create hono worker-old` follow prompts
- Crate Dockerfile as above
- Attempt to run
