### ISSUE TITLE
🚀 Feature Request: Add support for cross script workflow bindings for `getPlatformProxy`

### ISSUE THREAD

**Issue by aimproxy** [cloudflare/workers-sdk#7459]
### Describe the solution

```toml
[[workflows]]
name = "complete-app-installation-workflow"
binding = "COMPLETE_APP_INSTALLATION_WORKFLOW"
class_name = "CompleteAppInstallationWorkflow"
script_name = "complete-app-installation-worker"
```
