### ISSUE TITLE
🐛 BUG: service core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER: Worker refers to a service "core:user:worker", but no such service is defined.

### ISSUE THREAD

**Issue by flashblaze** [cloudflare/workers-sdk#7670]
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What versions are you using?

3.99.0 [wrangler], 4.20241230.0, [@cloudflare/workers-types]

### What operating system and version are you using?

WSL Ubuntu

### Describe the Bug

I'm using Nuxt with Workers Static Assets. When I deploy my app, Durable Objects work. However, it does not work in dev server.

wrangler.toml
```toml
#:schema node_modules/wrangler/config-schema.json
name = "dummy-worker"
main = "./worker-entry.mjs"
compatibility_date = "2025-01-04"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./.output/public/", binding = "ASSETS" }

[observability]
enabled = true

[vars]
NODE_VERSION = "20.17.0"
PNPM_VERSION = "9.12.3"

[[durable_objects.bindings]]
name = "DUMMY_OBJECT"
class_name = "DummyDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]

[[migrations]]
tag = "v2"
renamed_classes = [
    { from = "MyDurableObject", to = "DummyDurableObject" },
]
```

worker-entry.mjs
```js
// worker-entry.mjs
export { default } from './.output/server/index.mjs';
export { DummyDurableObject} from './functions/durable.ts';
```

worker-configuration.d.ts
```ts
// Generated by Wrangler by running `wrangler types`

interface Env {
	NODE_VERSION: "20.17.0";
	PNPM_VERSION: "9.12.3";
	DUMMY_OBJECT: DurableObjectNamespace<import("./worker-entry").DummyDurableObject>;
	ASSETS: Fetcher;
}
```

package,json
```json
{
  "name": "dummy-worker",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "pnpm run build && wrangler dev",
    "postinstall": "nuxt prepare",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix",
    "deploy": "pnpm run build && wrangler deploy",
    "cf-typegen": "wrangler types"
  },
  "dependencies": {
    "@nuxt/eslint": "^0.7.2",
    "@primevue/themes": "^4.2.5",
    "nuxt": "^3.15.0",
    "primevue": "^3.53.1",
    "shiki": "^1.26.1",
    "tailwindcss-primeui": "^0.3.4",
    "vue": "latest",
    "vue-router": "latest"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20241230.0",
    "@nuxt/eslint-config": "^0.7.4",
    "@nuxtjs/tailwindcss": "^6.12.2",
    "autoprefixer": "^10.4.20",
    "eslint": "^9.17.0",
    "h3": "^1.13.0",
    "nitro-cloudflare-dev": "^0.2.1",
    "nuxt-primevue": "3",
    "postcss": "^8.4.49",
    "tailwindcss": "^3.4.17",
    "typescript": "^5.7.2",
    "wrangler": "^3.99.0"
  }
}
```

nuxt.config.ts
```ts
import { defineNuxtConfig } from 'nuxt/config';

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  runtimeConfig: {
    environment: process.env.NODE_ENV || 'development'
  },
  modules: ['nuxt-primevue', '@nuxt/eslint', 'nitro-cloudflare-dev'],
  devtools: { enabled: true },
  css: ['~/assets/css/main.css', 'primevue/resources/themes/aura-light-green/theme.css'],
  compatibilityDate: '2025-01-04',
  nitro: {
    preset: 'cloudflare_module',
    experimental: {
      websocket: true,
    },
  },
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  eslint: {
    config: {
      autoInit: true,
      stylistic: {
        quotes: 'single',
        semi: true,
      },
    },
  },
  primevue: {
    components: {
      include: ['Button'],
    },
  },
});
```

### Please provide any relevant error logs

When i run `pnpm dev`, this is the log output

```sh
 ERROR  service core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER: Worker "core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER"'s binding "DummyDurableObject" refers to a service "core:user:worker", but no such service is defined.


 ERROR  Failed to initialize wrangler bindings proxy The Workers runtime failed to start. There is likely additional logging output above.

    at Miniflare2.#assembleAndUpdateConfig (node_modules/.pnpm/miniflare@3.20241218.0/node_modules/miniflare/src/index.ts:1404:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mutex.runWith (node_modules/.pnpm/miniflare@3.20241218.0/node_modules/miniflare/src/workers/shared/sync.ts:66:45)
    at async Miniflare2.#waitForReady (node_modules/.pnpm/miniflare@3.20241218.0/node_modules/miniflare/src/index.ts:1486:3)
    at async Miniflare2._getProxyClient (node_modules/.pnpm/miniflare@3.20241218.0/node_modules/miniflare/src/index.ts:1692:3)
    at async Miniflare2.getBindings (node_modules/.pnpm/miniflare@3.20241218.0/node_modules/miniflare/src/index.ts:1715:23)
    at async getPlatformProxy (node_modules/.pnpm/wrangler@3.99.0_@cloudflare+workers-types@4.20241230.0/node_modules/wrangler/wrangler-dist/cli.js:180408:20)
    at async _getPlatformProxy (node_modules/.pnpm/nitro-cloudflare-dev@0.2.1/node_modules/nitro-cloudflare-dev/dist/runtime/plugin.dev.mjs:48:17)
```
