### ISSUE TITLE
🐛 BUG: `service` should be an optional field under `[[services]]`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workers-sdk#7949]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What versions are you using?

3.106.0

### What operating system and version are you using?

MacOS

### Describe the Bug

AKA we should support self defined `WorkerEntrypoint` better.

Consider this worker

```ts
// ./src/server.ts
import { WorkerEntrypoint } from "cloudflare:workers";

export class MyWorker extends WorkerEntrypoint {
  someMethod() {
    return "hello " + Math.random();
  }
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    return Response.json(await env.MyWorker.someMethod());
  }
}

```

with this `wrangler.toml`:
```toml
name = "example-worker"
main = "src/server.ts"
compatibility_date = "2025-01-28"

[[services]]
binding = "MyWorker"
service = "example-worker" # this shouldn't be necessary
entrypoint = "MyWorker"
```

2 problems here: 

- `service = "example-worker"` shouldn't be ncessary since it's in the same worker. it should default to the main worker. but removing that line causes validation to fail. 
- when running `wrangler dev`, I get this output 

<img width="812" alt="Image" src="https://github.com/user-attachments/assets/95371460-82be-486e-9f81-6f96f7681c9d" />

That seems wrong, since it connects to itself successfully. Thankfully the worker still functions.
