### ISSUE TITLE
🐛 BUG: Vitest Integration fails in CI with Bun

### ISSUE THREAD

**Issue by vhscom** [cloudflare/workers-sdk#7969]
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration, C3 (npm create cloudflare), Workers Runtime

### What versions are you using?

3.103.2 [Wrangler], 4.20250121.0 [@cloudflare/workers-types], 0.6.4 [@cloudflare/vitest-pool-workers]

### What operating system and version are you using?

macOS 15.2 (24C101)

### Please provide a link to a minimal reproduction

https://github.com/vhscom/c3-minimal-workerd-ci-error

### Describe the Bug

Trying to run my workers through a test workflow in CI using GitHub Actions with `ubuntu-latest` and [receive an error](https://github.com/vhscom/private-landing/actions/runs/12878620829/job/35904850230):
```
test/index.spec.ts:
  
  # Unhandled error between tests
  -------------------------------
  error: Cannot find package 'cloudflare:test' from '/home/runner/work/c3-minimal-workerd-ci-error/c3-minimal-workerd-ci-error/test/index.spec.ts'
  -------------------------------
```

My action looks like:
```yaml
name: CI

on: push

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: |
                  bun install
                  bun pm untrusted

            - name: Run tests
              run: |
                  bun install
                  bun test
```

And the test failing:
```ts
describe('Hello World worker', () => {
	it('responds with Hello World! (unit style)', async () => {
		const request = new IncomingRequest('http://example.com');
		// Create an empty context to pass to `worker.fetch()`.
		const ctx = createExecutionContext();
		const response = await worker.fetch(request, env, ctx);
		// Wait for all `Promise`s passed to `ctx.waitUntil()` to settle before running test assertions
		await waitOnExecutionContext(ctx);
		expect(await response.text()).toMatchInlineSnapshot(`"Hello World!"`);
	});

	it('responds with Hello World! (integration style)', async () => {
		const response = await SELF.fetch('https://example.com');
		expect(await response.text()).toMatchInlineSnapshot(`"Hello World!"`);
	});
});
```

I expect the Vitest Integration to support both Node and Bun runtimes in a CI environment.

Thanks for all you do.

### Please provide any relevant error logs

If you'd like to see the error in CI for context, it's available on the minimal repro here:
https://github.com/vhscom/c3-minimal-workerd-ci-error/actions/runs/12880279876/job/35909036008
