### ISSUE TITLE
🐛 BUG: Durable Object will not be deleted

### ISSUE THREAD

**Issue by jacwright** [cloudflare/workers-sdk#8203]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What versions are you using?

3.109.2 [Wrangler], 18.20.2 [Node]

### What operating system and version are you using?

Mac

### Describe the Bug

I am deleting some durable objects and adding new ones. I have updated the bindings, but it still won't let me use the delete. Here is the output from the console:
```sh
% wrangler deploy --env test

 ⛅️ wrangler 3.109.2
--------------------

Total Upload: 458.51 KiB / gzip: 101.60 KiB
Your worker has access to the following bindings:
- Durable Objects:
  - RecordsEntity: RecordsEntity
  - Versioning: Versioning
  - Webhook: Webhook
  - ProjectImporter: ProjectImporter
- D1 Databases:
  - db: xxxxxx-test (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
- R2 Buckets:
  - storage: xxxxxx-test
- Vars:
  - ENVIRONMENT: "test"

✘ [ERROR] A request to the Cloudflare API (/accounts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/workers/scripts/xxxxxx-test) failed.

  Cannot apply --delete-class migration to class 'getClosestDurableObjectColo' without also removing
  the binding that references it. [code: 10061]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

And here is my wrangler.toml

```toml
name = "xxxxxx"
main = "src/index.ts"
compatibility_date = "2024-12-30"

### PRODUCTION ###

[vars]
ENVIRONMENT = "production"

[durable_objects]
bindings = [
  { name = "RecordsEntity", class_name = "RecordsEntity" },
  { name = "Versioning", class_name = "Versioning" },
  { name = "Webhook", class_name = "Webhook" },
  { name = "ProjectImporter", class_name = "ProjectImporter" },
]

[[r2_buckets]]
binding = "storage"
bucket_name = "storage"

[[d1_databases]]
binding = "db"
database_name = "xxxxxx"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[[migrations]]
tag = "v0.1"
new_classes = [
  "getClosestDurableObjectColo",
  "pool",
  "database",
  "autoVersion",
  "webhooks",
  "ProjectImporter",
]

[[migrations]]
tag = "v0.2"
new_sqlite_classes = ["RecordsEntity", "Versioning", "Webhook"]
deleted_classes = [
  "getClosestDurableObjectColo",
  "database",
  "pool",
  "autoVersion",
  "webhooks",
]

### TEST ###

[env.test.vars]
ENVIRONMENT = "test"

[env.test.durable_objects]
bindings = [
  { name = "RecordsEntity", class_name = "RecordsEntity" },
  { name = "Versioning", class_name = "Versioning" },
  { name = "Webhook", class_name = "Webhook" },
  { name = "ProjectImporter", class_name = "ProjectImporter" },
]

[[env.test.r2_buckets]]
binding = "storage"
bucket_name = "xxxxxx-test"

[[env.test.d1_databases]]
binding = "db"
database_name = "xxxxxx-test"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[[env.test.migrations]]
tag = "v0.1"
new_classes = [
  "getClosestDurableObjectColo",
  "pool",
  "database",
  "autoVersion",
  "webhooks",
  "ProjectImporter",
]

[[env.test.migrations]]
tag = "v0.2"
deleted_classes = [
  "getClosestDurableObjectColo",
  "database",
  "pool",
  "autoVersion",
  "webhooks",
]
new_sqlite_classes = ["RecordsEntity", "Versioning", "Webhook"]
```
