### ISSUE TITLE
🐛 BUG: Delete Classes Migration Failing

### ISSUE THREAD

**Issue by devceline** [cloudflare/workers-sdk#8210]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What versions are you using?

3.109.2 [Wrangler], 18.18.2 [Node]

### What operating system and version are you using?

Linux (Arch)

### Describe the Bug

After deploying a worker with a durable object `Create Migration` and bindings setup per environment, like this:
```toml
[[migrations]]
tag = "v1" 
new_classes = ["Foo"]

[env.staging]
durable_objects = { bindings = [
  { name = "Bar", class_name = "Foo" }
]}

[env.production]
durable_objects = { bindings = [
  { name = "Bar", class_name = "Foo" }
]}
```

Later then editing the `wrangler.toml` with a delete migration:
```toml
[[migrations]]
tag = "v1" 
new_classes = ["Foo"]

[[migrations]]
tag = "v2" 
deleted_classes = ["Foo"]

[env.staging]
durable_objects = { bindings = [] }

[env.production]
durable_objects = { bindings = [] }
```

running `wrangler deploy --env staging` gives the following error:
```
Cannot apply --delete-class migration to class 'Foo' without also removing the binding that references it. [code: 10061]
```

## Things I've tried
- Defining a default `durable_objects = { bindings = [] }`
- Erasing any mention of `durable_objects`
- Removing the first migration

### Please provide any relevant error logs

```
Cannot apply --delete-class migration to class 'Foo' without also removing the binding that references it. [code: 10061]
```
