### ISSUE TITLE
🐛 BUG: ERROR] A request to the Cloudflare API (/memberships) failed

### ISSUE THREAD

**Issue by mike-rambil** [cloudflare/workers-sdk#8277]
### Which Cloudflare product(s) does this pertain to?

Workers AI, Workers for Platforms

### What versions are you using?

1.13.8[@cloudflare/next-on-pages]

### What operating system and version are you using?

WSL v2

### Describe the Bug

Was trying to setup CD to deploy via github actions but I get this problem.

```
  Build Completed in .vercel/output [35s]
⚡️ Completed `npx vercel build`.
⚡️ Build Summary (@cloudflare/next-on-pages v1.13.8)
⚡️ 
⚡️ Prerendered Routes (3)
⚡️   ┌ /
⚡️   ├ /favicon.ico
⚡️   └ /index.rsc
⚡️ 
⚡️ Other Static Assets (26)
⚡️   ┌ /_app.rsc.json
⚡️   ├ /_document.rsc.json
⚡️   ├ /_error.rsc.json
⚡️   ├ /404.html
⚡️   └ ... 22 more
⚡️ Build log saved to '.vercel/output/static/_worker.js/nop-build-log.json'
⚡️ Generated '.vercel/output/static/_worker.js/index.js'.
⚡️ Build completed in 0.09s
✘ [ERROR] A request to the Cloudflare API (/memberships) failed.
  Unable to authenticate request [code: 10001]
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
Error: Process completed with exit code 1.



```

Workflow File:
```

name: Deploy on Version Release

on:
  release:
    types:
      - published  # This triggers the workflow when a release is published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Replace with the Node.js version you're using

      - name: Install dependencies
        run: npm install

      - name: Run deploy command
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}


```
