### ISSUE TITLE
🐛 BUG: erroneously reports "no bindings found" when using Workers Assets

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#8313]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What versions are you using?

wrangler 3.111.0

### What operating system and version are you using?

windows 11

### Describe the Bug

`wrangler.toml`:
```toml
name = "test"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[assets]
directory = "public"
binding = "ASSETS"
```

`src/index.ts`:
```ts
type Env = {
	ASSETS: Fetcher;
};

export default {
	async fetch(request, env, ctx): Promise<Response> {
		console.log(env);
		return new Response('Not found', { status: 404 });
	},
} satisfies ExportedHandler<Env>;
```

On startup, observe wrangler reporting "no bindings found":
```
 ⛅️ wrangler 3.111.0
--------------------

No bindings found.
```

But then if you log `env`, you'll see the assets binding as expected:
```
{ ASSETS: Fetcher {} }
```
