### ISSUE TITLE
🐛 BUG: TypeError after pages deployment

### ISSUE THREAD

**Issue by WilfSilver** [cloudflare/workers-sdk#8570]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What versions are you using?

4.2.0

### What operating system and version are you using?

Linux (Debian)

### Describe the Bug

Our GitLab pipelines have just started failing yesterday when running:

```sh
bunx wrangler pages deploy public --project-name=our_project --branch=dev
```

The deployment technically succeeds and is deployed to the main branch, but then the wrangler script fails with

```
✘ [ERROR] TypeError: The "options" argument must be of type object. Received an instance of AbortController
```

(see full error log attached)

We have since double-checked the wrangler version to confirm it is running 4.2.0

The full deployment script is:

```
deploy-frontend:
  stage: deploy
  tags:
    - shared_runner
  needs:
    - job: check-frontend
      artifacts: false
    - job: build-frontend
      artifacts: true
  before_script: *default_script
  script:
    - bunx wrangler pages deploy public --project-name=our_project --branch=dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      changes: *frontend_files
      when: always
```

But this has been unchanged since it was working fine (in older versions)

### Please provide any relevant error logs

```
$ bunx wrangler pages deploy public --project-name=our_project --branch=dev
Resolving dependencies
Resolved, downloaded and extracted [304]
Saved lockfile
Uploading... (15/17)
Uploading... (16/17)
Uploading... (17/17)
✨ Success! Uploaded 2 files (15 already uploaded) (2.39 sec)
🌎 Deploying...
✨ Deployment complete! Take a peek over at https://xxxxxxxx.our_project.pages.dev/
✘ [ERROR] TypeError: The "options" argument must be of type object. Received an instance of AbortController
      at validateObject (unknown)
      at setTimeoutPromise (node:timers/promises:22:19)
      at <anonymous> (/tmp/bunx-0-wrangler@latest/node_modules/wrangler/wrangler-dist/cli.js:148729:31)
      at processTicksAndRejections (native:7:39)
🪵  Logs were written to "/root/.config/.wrangler/logs/wrangler-2025-03-19_09-14-57_065.log"
Cleaning up project directory and file based variables
```
