### ISSUE TITLE
🐛 BUG: no environment found in configuration

### ISSUE THREAD

**Issue by cazcik** [cloudflare/workers-sdk#8701]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What versions are you using?

4.5.0

### What operating system and version are you using?

macOS Sequoia 15.3.1

### Describe the Bug

`wrangler deploy` is having trouble when passing `--env` stating the env does not exist even though it is described in `wrangler.jsonc`.

the deploy still completes however since it was unable to find the specified environment it does not get pushed with the corresponding environment's config.

## `wrangler.jsonc`
```
{
  "$schema": "./node_modules/wrangler/config-schema.json",
  "name": "myapp",
  "main": "./workers/app.ts",
  "compatibility_date": "2025-03-26",
  "compatibility_flags": ["nodejs_compat"],
  "upload_source_maps": true,
  "assets": {
    "directory": "./build/client",
  },
  "observability": {
    "enabled": true,
  },
  "env": {
    "development": {
      "vars": {
        "ENVIRONMENT": "development",
      },
    },
    "production": {
      "vars": {
        "ENVIRONMENT": "production",
      },
    },
  },
}
``` 

## deploy command

`pnpm wrangler deploy --env development`

## wrangler output

```
 ⛅️ wrangler 4.5.0
------------------

Using redirected Wrangler configuration.
 - Configuration being used: "build/server/wrangler.json"
 - Original user's configuration: "wrangler.jsonc"
 - Deploy configuration file: ".wrangler/deploy/config.json"
▲ [WARNING] Processing build/server/wrangler.json configuration:

    - No environment found in configuration with name "development".
      Before using `--env=development` there should be an equivalent environment section in the
  configuration.
  
      Consider adding an environment configuration section to the wrangler.json file:
      ```
      [env.development]
      ```
  


Attaching additional modules:
┌─────────────────────────────────┬──────┬─────────────┐
│ Name                            │ Type │ Size        │
├─────────────────────────────────┼──────┼─────────────┤
│ assets/app-DcVQ_KQR.js          │ esm  │ 284.51 KiB  │
├─────────────────────────────────┼──────┼─────────────┤
│ assets/server-build-6hK1RppR.js │ esm  │ 1080.95 KiB │
├─────────────────────────────────┼──────┼─────────────┤
│ Total (2 modules)               │      │ 1365.45 KiB │
└─────────────────────────────────┴──────┴─────────────┘
🌀 Building list of assets...
🌀 Starting asset upload...
🌀 Found 8 new or modified static assets to upload. Proceeding with upload...
+ /.gitkeep
+ /assets/manifest-0a33de6d.js
+ /assets/chunk-GNGMS2XR-eXYBZ-pF.js
+ /assets/home-Car_vtk_.js
+ /assets/root-wo9MWzK3.js
+ /assets/entry.client-FMuzxyuH.js
+ /assets/with-props-DeHwp1uX.js
+ /assets/root-B1ryitOf.css
Uploaded 2 of 8 assets
Uploaded 5 of 8 assets
Uploaded 8 of 8 assets
✨ Success! Uploaded 8 files (1.51 sec)

Total Upload: 1365.57 KiB / gzip: 266.50 KiB
Worker Startup Time: 11 ms
No bindings found.
Uploaded myapp-development (7.10 sec)
Deployed myapp-development triggers (0.70 sec)
  https://myapp.myworker.workers.dev
Current Version ID: a7a3741e-e96e-4238-9155-62e8d95bfc84
```

**Comment by cazcik** [comment]
this may be because i am using `@react-router/dev` version `7.4.0` which still has a peer dependency for `wrangler@^3.28.2`.

my suspicion is `wrangler@^3.28.2` does not support the new wrangler config and it seems to be the case judging from the built `wrangler.json`

```
{
  "configPath": "/Users/myname/code/myapp/wrangler.jsonc",
  "userConfigPath": "/Users/myname/code/myapp/wrangler.jsonc",
  "topLevelName": "myapp",
  "legacy_env": true,
  "compatibility_date": "2025-03-26",
  "compatibility_flags": ["nodejs_compat"],
  "jsx_factory": "React.createElement",
  "jsx_fragment": "React.Fragment",
  "rules": [{ "type": "ESModule", "globs": ["**/*.js", "**/*.mjs"] }],
  "name": "domi",
  "main": "index.js",
  "triggers": { "crons": [] },
  "assets": { "directory": "../client" },
  "preview_urls": true,
  "vars": {},
  "durable_objects": { "bindings": [] },
  "workflows": [],
  "migrations": [],
  "kv_namespaces": [],
  "cloudchamber": {},
  "send_email": [],
  "queues": { "producers": [], "consumers": [] },
  "r2_buckets": [],
  "d1_databases": [],
  "vectorize": [],
  "hyperdrive": [],
  "services": [],
  "analytics_engine_datasets": [],
  "dispatch_namespaces": [],
  "mtls_certificates": [],
  "pipelines": [],
  "logfwdr": { "bindings": [] },
  "observability": { "enabled": true },
  "dev": {
    "ip": "localhost",
    "local_protocol": "http",
    "upstream_protocol": "http"
  },
  "no_bundle": true
}

```

seems like a fix was just [merged](https://github.com/remix-run/react-router/pull/13258) so hopefully the next release will include it and fix this? i have yet to test with a `wrangler.toml` file however.

**Comment by jamesopstad** [comment]
When using the Cloudflare Vite plugin, the environment is selected at dev and build time rather than when running `wrangler deploy`. The current documentation for this is here - https://github.com/cloudflare/workers-sdk/tree/main/packages/vite-plugin-cloudflare#cloudflare-environments - but we're working on moving this to the docs site and making it a lot clearer. We also have a PR to improve the messaging about this if you try to run `wrangler deploy --env` in a project using the Vite plugin. Apologies for the confusion.

**Comment by ninjasitm** [comment]
Hello,

I'm experiencing this issue with a NUXT project:

```bash
Using redirected Wrangler configuration.
 - Configuration being used: "_worker.js/wrangler.json"
 - Original user's configuration: "../wrangler.toml"
 - Deploy configuration file: "../.wrangler/deploy/config.json"

✘ [ERROR] Processing _worker.js/wrangler.json configuration:

    - You have specified the environment "production", but are using a redirected configuration,
  produced by a build tool such as Vite.
      You need to set the environment in your build tool, rather than via Wrangler.
      For example, if you are using Vite, refer to these docs:
  https://developers.cloudflare.com/workers/vite-plugin/reference/cloudflare-environments/
```

I've used the following commands:


```
 CLOUDFLARE_ENV=production npx nuxt build
 CLOUDFLARE_ENV=production npx wrangler pages deploy
```

And here's my wrangler.toml file:

```toml
# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "---"
compatibility_date = "2025-03-27"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
[placement]
mode = "smart"

# Bindings
# Bindings allow your Worker to interact with resources on the Cloudflare Developer Platform, including
# databases, object storage, AI inference, real-time communication and more.
# https://developers.cloudflare.com/workers/runtime-apis/bindings/

[[r2_buckets]]
binding = "R2"
bucket_name = "---"

[[kv_namespaces]]
binding = "KV"
id = "nitm-connections"

[queues]
[[queues.producers]]
binding = "QUEUE"
queue = "---"
```
The build is successful until the error above during wrangler deploy. Any help here? I've followed the documentation and tried deploying with he env variable prexing the command but no success.
