### ISSUE TITLE
Bundling rules not working with prefix globs

### ISSUE THREAD

**Issue by SharzyL** [cloudflare/workers-sdk#9018]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What versions & operating system are you using?

Wrangler 4.12.0, node 22.14.0, yarn 1.22.22

### Describe the Bug

Minimal reproduction
```toml
# wrangler.toml
name = "example"
compatibility_date = "2022-02-28"
main = "src/index.ts"

[[rules]]
type = "Text"
globs = ["assets/**.md"]
fallthrough = true
```

```js
// src/index.js
import b from "../assets/a.md"

export default {
	async fetch(request: Request): Promise<Response> {
		console.log(b)
		return new Response(`${request.url}`);
	},
};
```

When I run `wrangler deploy --dry-run --outdir=dist`, it emits the following error:

```
 ⛅️ wrangler 4.12.0
-------------------


✘ [ERROR] Build failed with 1 error:

  ✘ [ERROR] No loader is configured for ".md" files:
  assets/a.md
  
      src/index.ts:1:14:
        1 │ import b from "../assets/a.md"
          ╵               ~~~~~~~~~~~~~~~~
```

If I change `assets/**` to `**/assets/**`, the error disappears. However, in this case `worker-configuration.d.ts` generated with `wrangler types` is no longer accepted by tsc:
```console
$ tsc --noEmit
worker-configuration.d.ts:9:16 - error TS5061: Pattern '*/assets/*' can have at most one '*' character.

9 declare module "*/assets/*" {
                 ~~~~~~~~~~~~


Found 1 error in worker-configuration.d.ts:9
```

I cannot find an approach to specify globs by path prefix that works both for wrangler and tsc.
