### ISSUE TITLE
`wrangler types` command do not create KV Namespace types if they are nested in environments.

### ISSUE THREAD

**Issue by Kjaer** [cloudflare/workers-sdk#9709]
### What versions & operating system are you using?

wrangler. 4.20.5, node.js 23.11.1, macos and linux (CI pipeline OS)

### Please provide a link to a minimal reproduction

https://github.com/Kjaer/wrangler-kv-namespace-type-problem

### Describe the Bug

I have following `wrangler.toml` file:

```toml
name = "my-worker"
main = "src/index.ts"
upload_source_maps = true
account_id = "xxxxxxxxxxxx"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[env.feature]
name = "my-worker-feature"

[[env.feature.kv_namespaces]]
binding = "MY_STORAGE_FEATURE"
id = "xxxxxxxxxxxx

[env.feature.vars]
DEPLOY_ENV = "feature"
SPACE_ID = "xxxxxxx"
ENVIRONMENT = "feature-environment"
FETCH_ENTRY_LIMIT = 1000
CACHE_DEFAULT_TTL_SECONDS = 3600
```

And I have similar 3 different environments in my `wrangler.toml` file too.

When I ran `npx wrangler types` it perfectly creates type definitions for environment variables. But it cannot create type definitions for KV Namespaces.

So I had to repeat KV Namespaces information on root level like this:
```toml
name = "my-worker"
main = "src/index.ts"
upload_source_maps = true
account_id = "xxxxxxxxxxxx"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
[[kv_namespaces]]
binding = "MY_STORAGE_FEATURE"
id = "xxxxxxxxxxxx


[env.feature]
name = "my-worker-feature"

[[env.feature.kv_namespaces]]
binding = "MY_STORAGE_FEATURE"
id = "xxxxxxxxxxxx

[env.feature.vars]
DEPLOY_ENV = "feature"
SPACE_ID = "xxxxxxx"
ENVIRONMENT = "feature-environment"
FETCH_ENTRY_LIMIT = 1000
CACHE_DEFAULT_TTL_SECONDS = 3600
```

now `npx wrangler types` create type definitions for my KV namespaces. Eventhough I am getting warnings during deployment it still works. Yet this is not usual.

**Comment by penalosa** [comment]
KV Namespaces are not shared between environments, so in general we recommend that if you have a KV namespace (etc..) in one environment it should also be in all other environments.

However, I agree that it's confusing that env vars are typed across environments while other bindings are not. We should fix that.

As a workaround, using `wrangler types -e feature` should give you the behaviour you want.

**Comment by Kjaer** [comment]
sweet! that'll do for now. I will adjust my CI deployment scripts passing environment for type generations and I think it will work. Thanks @penalosa.

I will create a new issue on the documentation, so we can add this `wrangler types -e feature` command to there, I hope everyone can benefit from it. Does that sound good?

**Comment by Kjaer** [comment]
Alright, I tried `wrangler types -e feature` but it didn't actually work. Unfortunately typechecks are failing. Because I have KV Namespace per environment and I get to decide on runtime which KV Namespace I need to use. So Typescript expects all possible KV Namespace _name_ 

I tried `wrangler types -e feature,qa,prod` and was hoping get all KV Namespace typedefinitions yet no luck.

I end up creating a dummy environment for only KV Namespaces as follows:
```toml
[env.storage]
[[env.storage.kv_namespaces]]
binding = "MY_STORAGE_FEATURE"
id = "xxxxx"

[[env.storage.kv_namespaces]]
binding = "MY_STORAGE_QA"
id = "xxxxx"

[[env.storage.kv_namespaces]]
binding = "MY_STORAGE_PROD"
id = "xxxxxx"
```

and now warnings are gone. Still a fix would be nice.
